### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 821: invalid continuation byte

### ISSUE THREAD

**Issue by danti1988** [SecuraBV/Timeroast#1]
Getting this error when running with Rockyou wordlist 

Traceback (most recent call last):
  File "/Timeroast/timeroast/./timecrack.py", line 60, in <module>
    main()
  File "/Timeroast/timeroast/./timecrack.py", line 53, in main
    for rid, password in try_crack(args.hashes, args.dictionary):
  File "/Timeroast/timeroast/./timecrack.py", line 31, in try_crack
    for password in dictfile:
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 821: invalid continuation byte

**Comment by goosvorbook** [comment]
In addition to this, other wordlists seem to work fine, for example xato-net-10-million-passwords-dup.txt has no issues

**Comment by TomTervoort** [comment]
Sorry for the two-years late reply! Maybe this'll still be useful for someone.

The reason the rockyou list doesn't work is that it appears to use the legacy latin-1 character encoding, whereas the script expects UTF-8. If you preprocess it with an encoding coverter (e.g. `iconv -f ISO-8859-1 -t UTF-8 rockyou.txt > rockyou-utf8.txt`) it should work with the script.

However, the timecrack script is pretty slow with large dictionaries. I'd recommend to use Hashcat instead, which can now directly process the output of the timeroast script as well.
