### ISSUE TITLE
 Only one usage of each socket address (protocol/network address/port) is normally permitted

### ISSUE THREAD

**Issue by TazDevl74** [SecuraBV/Timeroast#2]
C:\Temp\Timeroast\timeroast>timeroast.py <redacted>
Traceback (most recent call last):
  File "C:\Temp\Timeroast\timeroast\timeroast.py", line 145, in <module>
    main()
  File "C:\Temp\Timeroast\timeroast\timeroast.py", line 140, in main
    for rid, hashval, salt in ntp_roast(args.dc, args.rids, args.rate, args.timeout):
  File "C:\Temp\Timeroast\timeroast\timeroast.py", line 32, in ntp_roast
    sock.bind(('0.0.0.0', 123))
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

I'm getting this error in my testlab and in a production env.

**Comment by TomTervoort** [comment]
This is probably conflicting with the existing NTP service on your system (probably W32Time). If you run the script without supplying a `-p`/`--src-port` flag it will pick a random source port, which should work in most cases.

If it doesn't (e.g. because a firewall blocks NTP traffic not originating from port 123) then you can try turning off the Windows Time Service before running the script.
